tool: update xpanes version because why not

diff --git a/bin/.local/bin/xpanes b/bin/.local/bin/xpanes
--- a/bin/.local/bin/xpanes
+++ b/bin/.local/bin/xpanes
@@ -5,7 +5,7 @@ readonly XP_SHELL="/usr/bin/env bash"
 # @Filename xpanes
 
 set -u
-readonly XP_VERSION="4.1.3"
+readonly XP_VERSION="4.1.4"
 
 ## trap might be updated in 'xpns_pre_execution' function
 trap 'rm -f "${XP_CACHE_HOME}"/__xpns_*$$; xpns_clean_session' EXIT
@@ -126,6 +126,7 @@ XP_WINDOW_WIDTH=
 XP_WINDOW_HEIGHT=
 XP_COLS=
 XP_COLS_OFFSETS=
+XP_OPT_INTERVAL=0
 XP_OPT_DEBUG=0
 XP_OPT_IGNORE_SIZE_LIMIT=0
 
@@ -212,9 +213,11 @@ OPTIONS:
   --ssh                        Same as \`-t -s -c 'ssh -o StrictHostKeyChecking=no {}'\`.
   --stay                       Do not switch to new window.
   --bulk-cols=NUM1[,NUM2 ...]  Set number of columns on multiple rows (i.e, "2,2,2" represents 2 cols x 3 rows).
+  --interval=<seconds>         Set interval between each pane creation and each command execution.
+                               sleep(1) is used for the interval.
   --debug                      Print debug message.
 
-Copyright (c) 2021 Yamada, Yasuhiro
+Copyright (c) 2023 Yamada, Yasuhiro
 Released under the MIT License.
 https://github.com/greymd/tmux-xpanes
 USAGE
@@ -326,6 +329,13 @@ xpns_restore_allow_rename()  {
     else
       ${TMUX_XPANES_EXEC} -S "${_session}" set-window-option -g allow-rename on
     fi
+  fi
+}
+
+xpns_interval() {
+  local _interval="$1"
+  if [[ -n "${_interval-}" ]] && [[ "${_interval}" != "0" ]]; then
+    sleep "${_interval}"
   fi
 }
 
@@ -664,9 +674,12 @@ xpns_notify_logging() {
 xpns_notify_sync() {
   local _window_name="$1"
   shift
+  local _interval="$1"
+  shift
   local _args_num=$(($# - 1))
   for i in $(xpns_seq 0 "${_args_num}"); do
-    xpns_notify "sync_${_window_name}-${i}-$$" &
+    xpns_interval "${_interval}"
+    xpns_notify "sync_${_window_name}-${i}-$$"
   done
 }
 
@@ -677,7 +690,13 @@ xpns_is_window_alive() {
   shift
   local _def_allow_rename="$1"
   shift
-  if ! ${TMUX_XPANES_EXEC} display-message -t "$_window_name" -p > /dev/null 2>&1; then
+  local _window_name_on_tmux _exit_status
+  # Check not only exit status but also the if the window id is empty,
+  # because the exit status of display-message is
+  # no longer available from tmux version 3.2 (GitHub Issue #175)
+  _window_name_on_tmux=$(${TMUX_XPANES_EXEC} display-message -t "$_window_name" -p '#{window_id}')
+  _exit_status=$?
+  if [[ $_exit_status -ne 0 ]] || [[ -z "$_window_name_on_tmux" ]]; then
     xpns_msg_info "All the panes are closed before displaying the result."
     if [[ "${_speedy_await_flag}" -eq 0 ]]; then
       xpns_msg_info "Use '-s' option instead of '-ss' option to avoid this behavior."
@@ -740,6 +759,8 @@ xpns_send_commands() {
   shift
   local _index_offset="$1"
   shift
+  local _interval="$1"
+  shift
   local _repstr="$1"
   shift
   local _cmd="$1"
@@ -748,6 +769,7 @@ xpns_send_commands() {
   local _pane_index=
   local _exec_cmd=
   for arg in "$@"; do
+    xpns_interval "${_interval}"
     _exec_cmd="${_cmd//${_repstr}/${arg}}"
     _pane_index=$((_index + _index_offset))
     ${TMUX_XPANES_EXEC} send-keys -t "${_window_name}.${_pane_index}" "${_exec_cmd}" C-m
@@ -817,6 +839,8 @@ xpns_split_window() {
   shift
   local _await_flag="$1"
   shift
+  local _interval="$1"
+  shift
   local _pane_base_index="$1"
   shift
   local _repstr="$1"
@@ -832,10 +856,9 @@ xpns_split_window() {
     xpns_msg_debug "Index:${i} Argument:${args[i]}"
     _sep_count=$((_sep_count + 1))
     _exec_cmd="${_cmd_template//${_repstr}/${args[i]}}"
-
+    xpns_interval "${_interval}"
     ## Speedy mode
     if [[ $_speedy_flag -eq 1 ]]; then
-
       _exec_cmd=$(xpns_inject_wait_command "${_log_flag}" "${_title_flag}" "${_speedy_flag}" "${_await_flag}" "$i" "${_exec_cmd}")
       # Execute command as a child process of default-shell.
       ${TMUX_XPANES_EXEC} split-window -t "${_window_name}" -h -d "${_exec_cmd}"
@@ -869,6 +892,8 @@ xpns_prepare_extra_panes() {
   shift
   local _await_flg="$1"
   shift
+  local _interval="$1"
+  shift
   # specify a pane which has the biggest index number.
   #   Because pane_id may not be immutable.
   #   If the small number of index is specified here, correspondance between pane_title and command can be slip off.
@@ -881,6 +906,7 @@ xpns_prepare_extra_panes() {
     "${_title_flag}" \
     "${_speedy_flg}" \
     "${_await_flg}" \
+    "${_interval}" \
     "${_pane_base_index}" \
     "$@"
 }
@@ -1006,6 +1032,8 @@ xpns_prepare_window()  {
   shift
   local _await_flg="$1"
   shift
+  local _interval="$1"
+  shift
   local _repstr="$1"
   shift
   local _cmd_template="$1"
@@ -1045,6 +1073,7 @@ xpns_prepare_window()  {
     xpns_msg_debug "_col=$_col"
     ((_offset = _cols_offset[i]))
     for ((j = 0; j < _col; j++)); do
+      xpns_interval "${_interval}"
       if ((j == 0)); then
         ((idx = _offset - _col))
         # Create new row
@@ -1077,6 +1106,7 @@ xpns_prepare_window()  {
   _col="${_cols[0]}"
   _cell_width=$(((_window_width - _col + 1) / _col))
   for ((j = 1; j < _col; j++)); do
+    xpns_interval "${_interval}"
     idx=$((_cols_offset[0] - j))
     # Adjust width
     _current_pane_width=$(${TMUX_XPANES_EXEC} display-message -t "$_first_pane_id" -p '#{pane_width}' | head -n 1)
@@ -1138,6 +1168,8 @@ xpns_prepare_preset_layout_window() {
   shift
   local _await_flg="$1"
   shift
+  local _interval="$1"
+  shift
   # Create new window.
   if [[ "${_attach_flg}" -eq 1 ]]; then
     ${TMUX_XPANES_EXEC} new-window -n "${_window_name}"
@@ -1156,6 +1188,7 @@ xpns_prepare_preset_layout_window() {
     "${_title_flag}" \
     "${_speedy_flg}" \
     "${_await_flg}" \
+    "${_interval}" \
     "${_pane_base_index}" \
     "$@"
 
@@ -1518,8 +1551,9 @@ xpns_execution() {
   ## Fix window size and define pane size
   {
     local  _tmp_col_row_cols _tmp_cols
-    IFS=" " read -r XP_WINDOW_HEIGHT XP_WINDOW_WIDTH < \
-      <(${TMUX_XPANES_EXEC} display-message -p '#{window_height} #{window_width}')
+    IFS=" " read -r XP_WINDOW_HEIGHT XP_WINDOW_WIDTH < <(
+      ${TMUX_XPANES_EXEC} display-message -p '#{window_height} #{window_width}'
+    )
     if [[ -n "${XP_OPT_BULK_COLS}" ]]; then
       _tmp_col_row_cols="$(xpns_check_cell_size_bulk \
         "${#XP_ARGS[@]}" \
@@ -1581,6 +1615,7 @@ xpns_execution() {
       "${XP_OPT_SET_TITLE}" \
       "${XP_OPT_SPEEDY}" \
       "${XP_OPT_SPEEDY_AWAIT}" \
+      "${XP_OPT_INTERVAL}" \
       "${XP_REPSTR}" \
       "${XP_CMD_UTILITY}" \
       "${XP_ARGS[@]}"
@@ -1593,6 +1628,7 @@ xpns_execution() {
       "${XP_OPT_ATTACH}" \
       "${XP_OPT_SPEEDY}" \
       "${XP_OPT_SPEEDY_AWAIT}" \
+      "${XP_OPT_INTERVAL}" \
       "${XP_REPSTR}" \
       "${XP_CMD_UTILITY}" \
       "${XP_ARGS[@]}"
@@ -1604,6 +1640,7 @@ xpns_execution() {
       "${XP_OPT_ATTACH}" \
       "${XP_OPT_SPEEDY}" \
       "${XP_OPT_SPEEDY_AWAIT}" \
+      "${XP_OPT_INTERVAL}" \
       "${XP_REPSTR}" \
       "${XP_CMD_UTILITY}" \
       "${XP_ARGS[@]}"
@@ -1654,6 +1691,7 @@ xpns_execution() {
   if [[ $XP_OPT_SPEEDY -eq 1 ]]; then
     xpns_notify_sync \
       "${_window_name}" \
+      "${XP_OPT_INTERVAL}" \
       "${XP_ARGS[@]}"
   fi
 
@@ -1666,6 +1704,7 @@ xpns_execution() {
     xpns_send_commands \
       "${_window_name}" \
       "${_pane_base_index}" \
+      "${XP_OPT_INTERVAL}" \
       "${XP_REPSTR}" \
       "${XP_CMD_UTILITY}" \
       "${XP_ARGS[@]}"
@@ -1824,6 +1863,17 @@ xpns_opt_check_num() {
   exit ${XP_EINVAL}
 }
 
+xpns_opt_check_float() {
+  local _option="$1"
+  shift
+  local _arg="$1"
+  if [[ -n "$_arg" ]] && [[ -z "${_arg//[0-9.]/}" ]]; then
+    return 0
+  fi
+  xpns_msg_error "Invalid argument '$_arg' for $_option option"
+  exit ${XP_EINVAL}
+}
+
 xpns_opt_check_str() {
   local _option="$1"
   shift
@@ -1945,6 +1995,13 @@ xpns_parse_options() {
         XP_OPTIONS+=("$1")
         shift
         ;;
+      --interval)
+        xpns_opt_check_float "$opt" "$1"
+        XP_OPTIONS+=("$opt")
+        XP_OPT_INTERVAL="$1"
+        XP_OPTIONS+=("$1")
+        shift
+        ;;
       --debug)
         XP_OPTIONS+=("$opt")
         XP_OPT_DEBUG=1
@@ -1953,7 +2010,7 @@ xpns_parse_options() {
         XP_OPTIONS+=("$opt")
         XP_OPT_DRY_RUN=1
         ;;
-      --ignore-size-limit)
+      --ignore-size-limit)   # Hidden for testing
         XP_OPTIONS+=("$opt")
         XP_OPT_IGNORE_SIZE_LIMIT=1
         ;;
